import type { Metadata } from 'next';
// import { Inter as FontSans } from 'next/font/google';
import { notFound } from 'next/navigation';
import Providers from '@/components/Providers';
import { cn } from '@/lib/utils';
import '@/app/globals.css';

// export const fontSans = FontSans({
//   subsets: ['latin'],
//   variable: '--font-sans',
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const locales = ['en', 'zh-hant'];

// type ParamsProps = {
//   locale: string;
// };

type Props = {
  params: {
    locale: string;
  };
  children: React.ReactNode;
};

const RootLayout = ({ params, children }: Props) => {
  if (!locales.includes(params.locale)) notFound();

  return (
    <html lang={params.locale}>
      <body className={cn('min-h-screen bg-background font-sans antialiased scrollbar')}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export default RootLayout;
