import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { notFound } from 'next/navigation';
import Providers from '@/components/Providers';
import { cn } from '@/lib/utils';
import '@/app/globals.css';
import { PageProps } from '@/types/common';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const locales = ['en', 'zh-hant'];

type ParamsProps = {
  locale: string;
};

const RootLayout = ({ params, children }: PropsWithChildren<PageProps<ParamsProps>>) => {
  if (!locales.includes(params.locale)) notFound();

  return (
    <html lang={params.locale}>
      <body className={cn('min-h-screen bg-background font-sans antialiased scrollbar', fontSans.variable)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
};

export const dynamicParams = false;

export const generateStaticParams = async () => {
  const initialParams: ParamsProps[] = [{ locale: 'en' }, { locale: 'zh-hant' }];

  return initialParams;
};

export default RootLayout;
